CREATE TABLE orderitems (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    specialRequests TEXT NOT NULL,
    sizeReg TEXT NOT NULL,
    sizeSmall TEXT NOT NULL,
    priceReg DECIMAL NOT NULL,
    priceSmall DECIMAL NOT NULL,
    ingredients TEXT NOT NULL,
    quantity INTEGER DEFAULT 1 NOT NULL
);